parameters: {}
environment: {
  HELLO_BOT_API_KEY: '${HELLO_BOT_API_KEY}'
}
packages:
    - name: bot
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: hello-bot
          binary: false
          main: 'main'
          runtime: 'go:1.20'
          web: true
          webSecure: false
          parameters: {}
          environment: {}
          annotations: {}
          limits: {
            timeout: 3000,
            memory: 128,
            logs: 16
          }
